name: homegpt
description: "A cross-platform Flutter starter for the HomeGPT app."
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/config.json
    - assets/icon.png
